from __future__ import annotations

from importlib import import_module
from typing import Dict

_WORKFLOW_EXPORTS = [
    'SimulationContextBundle',
    'PaperExportBundle',
    'RiskDatasetBundle',
    'RiskTrainingFlowBundle',
    'UQBenchmarkFlowBundle',
    'analyze_signal_if_available',
    'build_risk_dataset_from_runner',
    'has_existing_risk_training_checkpoints',
    'has_existing_risk_model_artifacts',
    'load_existing_risk_dataset_artifact',
    'load_existing_risk_training_bundle',
    'has_existing_uq_benchmark_artifacts',
    'load_existing_uq_benchmark_bundle',
    'build_full_simulation_context',
    'export_paper_tables_and_figures',
    'configure_experiment_profile',
    'initialize_run_context',
    'report_export_bundle',
    'report_main_loop_bundle',
    'report_preflight_bundle',
    'report_quick_probe_bundle',
    'report_run_context',
    'report_signal_bundle',
    'report_surprise_gate_bundle',
    'resolve_main_loop_policy',
    'run_risk_training_flow',
    'run_main_loop_with_policy',
    'run_preflight_bundle',
    'run_quick_probe_with_auto_escalation',
    'run_surprise_gate_with_policy',
    'run_uq_benchmark_flow',
    'summarize_and_export_if_available',
    'train_and_calibrate_risk_model',
    'load_notebook_contract_manifest',
    'manifest_has_stage',
    'validate_notebook_contract_manifest',
    'write_notebook_contract_manifest',
]

__all__ = [
    'SearchConfig',
    'ClosedLoopConfig',
    'align_dataset_scale',
    'auto_select_shard_id',
    'BenchmarkBundle',
    'build_run_artifact_paths',
    'build_uq_artifact_paths',
    'build_closedloop_runner_and_splits',
    'configure_persistent_run_prefix',
    'diagnose_surprise_root_cause',
    'export_closedloop_artifacts',
    'initialize_configs',
    'inspect_shard_progress',
    'make_waymax_data_iter',
    'run_quick_surprise_probe',
    'run_risk_aware_closed_loop_step',
    'run_uq_benchmark',
    'resolve_latentdriver_checkpoint',
    'restore_artifacts_via_upload',
    'run_preflight_and_calibration',
    'run_surprise_quality_gate',
    'run_closed_loop',
    'save_surprise_signal_usefulness_artifacts',
    'plot_predictive_distribution_step',
    'preview_predictive_distribution_pair',
    'RiskControlSelection',
    'select_action_with_calibrated_risk',
    'shard_run_prefix',
    'summarize_controller_tradeoff',
    'summarize_method_outputs',
    'analyze_surprise_signal_usefulness',
    'ensure_drive_ready',
    'ensure_repo_checkout',
    'prepare_repo_imports',
    'run_cached_deterministic_setup',
] + _WORKFLOW_EXPORTS

_SYMBOL_MODULE: Dict[str, str] = {
    # config
    'SearchConfig': 'src.closedloop.config',
    'ClosedLoopConfig': 'src.closedloop.config',
    'align_dataset_scale': 'src.closedloop.config',
    'auto_select_shard_id': 'src.closedloop.config',
    'build_run_artifact_paths': 'src.closedloop.config',
    'build_uq_artifact_paths': 'src.closedloop.config',
    'configure_persistent_run_prefix': 'src.closedloop.config',
    'initialize_configs': 'src.closedloop.config',
    'inspect_shard_progress': 'src.closedloop.config',
    'resolve_latentdriver_checkpoint': 'src.closedloop.config',
    'restore_artifacts_via_upload': 'src.closedloop.config',
    'shard_run_prefix': 'src.closedloop.config',
    # risk benchmark/control
    'BenchmarkBundle': 'src.closedloop.risk_benchmark',
    'run_uq_benchmark': 'src.closedloop.risk_benchmark',
    'summarize_controller_tradeoff': 'src.closedloop.risk_benchmark',
    'RiskControlSelection': 'src.closedloop.risk_control',
    'run_risk_aware_closed_loop_step': 'src.closedloop.risk_control',
    'select_action_with_calibrated_risk': 'src.closedloop.risk_control',
    # calibration/core
    'diagnose_surprise_root_cause': 'src.closedloop.calibration',
    'run_surprise_quality_gate': 'src.closedloop.calibration',
    'build_closedloop_runner_and_splits': 'src.closedloop.core',
    'make_waymax_data_iter': 'src.closedloop.core',
    'run_quick_surprise_probe': 'src.closedloop.core',
    'run_preflight_and_calibration': 'src.closedloop.core',
    'run_closed_loop': 'src.closedloop.core',
    # artifact/signal/viz/runtime
    'export_closedloop_artifacts': 'src.closedloop.resume_io',
    'summarize_method_outputs': 'src.closedloop.resume_io',
    'analyze_surprise_signal_usefulness': 'src.closedloop.signal_analysis',
    'save_surprise_signal_usefulness_artifacts': 'src.closedloop.signal_analysis',
    'plot_predictive_distribution_step': 'src.closedloop.visualization',
    'preview_predictive_distribution_pair': 'src.closedloop.visualization',
    'ensure_drive_ready': 'src.closedloop.colab_runtime',
    'ensure_repo_checkout': 'src.closedloop.colab_runtime',
    'prepare_repo_imports': 'src.closedloop.colab_runtime',
    'run_cached_deterministic_setup': 'src.closedloop.colab_runtime',
    # workflows: closedloop flow
    'SimulationContextBundle': 'src.workflows.closedloop_flow',
    'analyze_signal_if_available': 'src.workflows.closedloop_flow',
    'build_full_simulation_context': 'src.workflows.closedloop_flow',
    'configure_experiment_profile': 'src.workflows.closedloop_flow',
    'initialize_run_context': 'src.workflows.closedloop_flow',
    'report_export_bundle': 'src.workflows.closedloop_flow',
    'report_main_loop_bundle': 'src.workflows.closedloop_flow',
    'report_preflight_bundle': 'src.workflows.closedloop_flow',
    'report_quick_probe_bundle': 'src.workflows.closedloop_flow',
    'report_run_context': 'src.workflows.closedloop_flow',
    'report_signal_bundle': 'src.workflows.closedloop_flow',
    'report_surprise_gate_bundle': 'src.workflows.closedloop_flow',
    'resolve_main_loop_policy': 'src.workflows.closedloop_flow',
    'run_main_loop_with_policy': 'src.workflows.closedloop_flow',
    'run_preflight_bundle': 'src.workflows.closedloop_flow',
    'run_quick_probe_with_auto_escalation': 'src.workflows.closedloop_flow',
    'run_surprise_gate_with_policy': 'src.workflows.closedloop_flow',
    'summarize_and_export_if_available': 'src.workflows.closedloop_flow',
    # workflows: risk/uq/paper
    'RiskDatasetBundle': 'src.workflows.risk_training_flow',
    'RiskTrainingFlowBundle': 'src.workflows.risk_training_flow',
    'build_risk_dataset_from_runner': 'src.workflows.risk_training_flow',
    'has_existing_risk_training_checkpoints': 'src.workflows.risk_training_flow',
    'has_existing_risk_model_artifacts': 'src.workflows.risk_training_flow',
    'load_existing_risk_dataset_artifact': 'src.workflows.risk_training_flow',
    'load_existing_risk_training_bundle': 'src.workflows.risk_training_flow',
    'run_risk_training_flow': 'src.workflows.risk_training_flow',
    'train_and_calibrate_risk_model': 'src.workflows.risk_training_flow',
    'UQBenchmarkFlowBundle': 'src.workflows.uq_benchmark_flow',
    'has_existing_uq_benchmark_artifacts': 'src.workflows.uq_benchmark_flow',
    'load_existing_uq_benchmark_bundle': 'src.workflows.uq_benchmark_flow',
    'run_uq_benchmark_flow': 'src.workflows.uq_benchmark_flow',
    'PaperExportBundle': 'src.workflows.paper_export_flow',
    'export_paper_tables_and_figures': 'src.workflows.paper_export_flow',
    'load_notebook_contract_manifest': 'src.workflows.notebook_contract',
    'manifest_has_stage': 'src.workflows.notebook_contract',
    'validate_notebook_contract_manifest': 'src.workflows.notebook_contract',
    'write_notebook_contract_manifest': 'src.workflows.notebook_contract',
}


def __getattr__(name: str):
    module_name = _SYMBOL_MODULE.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    mod = import_module(module_name)
    value = getattr(mod, name)
    globals()[name] = value
    return value
