from __future__ import annotations

import os
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Optional, Sequence

import pandas as pd


@dataclass
class SmartFinetuneResult:
    status: str
    repo_dir: str
    run_dir: str
    train_config_path: str
    val_config_path: str
    ckpt_dir: str
    latest_ckpt_path: str
    train_command: str
    val_command: str
    train_raw_dirs: List[str]
    val_raw_dirs: List[str]
    message: str = ""
    train_rc: int = 0
    val_rc: int = 0


def _normalize_dirs(values: Optional[Sequence[str]], fallback: str) -> List[str]:
    if values is None:
        return [str(fallback)]
    out = [str(v).strip() for v in values if str(v).strip()]
    return out if len(out) > 0 else [str(fallback)]


def _run_command(cmd: List[str], cwd: Optional[str] = None) -> subprocess.CompletedProcess:
    print("[smart-ft] $", " ".join(cmd))
    return subprocess.run(cmd, cwd=cwd, check=False)


def _ensure_smart_repo(
    repo_dir: str,
    repo_url: str = "https://github.com/rainmaker22/SMART.git",
    branch: str = "main",
    update_if_exists: bool = False,
) -> Path:
    repo_path = Path(str(repo_dir)).expanduser()
    if not repo_path.exists():
        repo_path.parent.mkdir(parents=True, exist_ok=True)
        rc = _run_command(
            ["git", "clone", "--depth", "1", "-b", str(branch), str(repo_url), str(repo_path)],
            cwd=str(repo_path.parent),
        )
        if rc.returncode != 0:
            raise RuntimeError(f"Failed to clone SMART repo from {repo_url} to {repo_path}")
    elif update_if_exists:
        _run_command(["git", "pull", "--ff-only"], cwd=str(repo_path))
    return repo_path


def _yaml_list(items: Iterable[str]) -> str:
    return "[" + ", ".join([f'"{str(x)}"' for x in items]) + "]"


def _write_train_config(
    out_path: Path,
    train_raw_dirs: Sequence[str],
    val_raw_dirs: Sequence[str],
    train_processed_dir: str,
    val_processed_dir: str,
    max_epochs: int,
    accelerator: str,
    devices: int,
    num_workers: int,
    train_batch_size: int,
    val_batch_size: int,
    total_steps: int,
    warmup_steps: int,
    lr: float,
    num_future_steps: int,
) -> None:
    txt = f"""# Auto-generated by src.platform.smart_finetune
time_info: &time_info
  num_historical_steps: 11
  num_future_steps: {int(num_future_steps)}
  use_intention: True
  token_size: 2048

Dataset:
  root:
  train_batch_size: {int(train_batch_size)}
  val_batch_size: {int(val_batch_size)}
  test_batch_size: 1
  shuffle: True
  num_workers: {int(num_workers)}
  pin_memory: True
  persistent_workers: {str(int(num_workers) > 0)}
  train_raw_dir: {_yaml_list(train_raw_dirs)}
  val_raw_dir: {_yaml_list(val_raw_dirs)}
  test_raw_dir:
  transform: WaymoTargetBuilder
  train_processed_dir: "{str(train_processed_dir)}"
  val_processed_dir: "{str(val_processed_dir)}"
  test_processed_dir:
  dataset: "scalable"
  <<: *time_info

Trainer:
  strategy: ddp_find_unused_parameters_false
  accelerator: "{str(accelerator)}"
  devices: {int(devices)}
  max_epochs: {int(max_epochs)}
  save_ckpt_path:
  num_nodes: 1
  mode:
  ckpt_path:
  precision: 32
  accumulate_grad_batches: 1

Model:
  mode: "train"
  predictor: "smart"
  dataset: "waymo"
  input_dim: 2
  hidden_dim: 128
  output_dim: 2
  output_head: False
  num_heads: 8
  <<: *time_info
  head_dim: 16
  dropout: 0.1
  num_freq_bands: 64
  lr: {float(lr)}
  warmup_steps: {int(warmup_steps)}
  total_steps: {int(total_steps)}
  decoder:
    <<: *time_info
    num_map_layers: 3
    num_agent_layers: 6
    a2a_radius: 60
    pl2pl_radius: 10
    pl2a_radius: 30
    time_span: 30
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(txt)


def _write_val_config(
    out_path: Path,
    val_raw_dirs: Sequence[str],
    val_processed_dir: str,
    accelerator: str,
    devices: int,
    num_workers: int,
    batch_size: int,
    total_steps: int,
    warmup_steps: int,
    lr: float,
    num_future_steps: int,
) -> None:
    txt = f"""# Auto-generated by src.platform.smart_finetune
time_info: &time_info
  num_historical_steps: 11
  num_future_steps: {int(num_future_steps)}
  token_size: 2048

Dataset:
  root:
  batch_size: {int(batch_size)}
  shuffle: True
  num_workers: {int(num_workers)}
  pin_memory: True
  persistent_workers: {str(int(num_workers) > 0)}
  train_raw_dir:
  val_raw_dir: {_yaml_list(val_raw_dirs)}
  test_raw_dir:
  TargetBuilder: WaymoTargetBuilder
  train_processed_dir:
  val_processed_dir: "{str(val_processed_dir)}"
  test_processed_dir:
  dataset: "scalable"
  <<: *time_info

Trainer:
  strategy: ddp_find_unused_parameters_false
  accelerator: "{str(accelerator)}"
  devices: {int(devices)}
  max_epochs: 1
  save_ckpt_path:
  num_nodes: 1
  mode:
  ckpt_path:
  precision: 32
  accumulate_grad_batches: 1

Model:
  mode: "validation"
  predictor: "smart"
  dataset: "waymo"
  input_dim: 2
  hidden_dim: 128
  output_dim: 2
  output_head: False
  num_heads: 8
  <<: *time_info
  head_dim: 16
  dropout: 0.1
  num_freq_bands: 64
  lr: {float(lr)}
  warmup_steps: {int(warmup_steps)}
  total_steps: {int(total_steps)}
  decoder:
    <<: *time_info
    num_map_layers: 3
    num_agent_layers: 6
    a2a_radius: 60
    pl2pl_radius: 10
    pl2a_radius: 30
    time_span: 30
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(txt)


def _latest_ckpt(ckpt_dir: Path) -> str:
    if not ckpt_dir.exists():
        return ""
    cands = sorted(ckpt_dir.glob("*.ckpt"), key=lambda p: p.stat().st_mtime, reverse=True)
    return str(cands[0]) if len(cands) > 0 else ""


def smart_finetune_summary_df(result: SmartFinetuneResult) -> pd.DataFrame:
    return pd.DataFrame(
        [
            {
                "status": str(result.status),
                "repo_dir": str(result.repo_dir),
                "run_dir": str(result.run_dir),
                "latest_ckpt_path": str(result.latest_ckpt_path),
                "train_rc": int(result.train_rc),
                "val_rc": int(result.val_rc),
                "train_raw_dirs": "|".join(result.train_raw_dirs),
                "val_raw_dirs": "|".join(result.val_raw_dirs),
                "message": str(result.message),
            }
        ]
    )


def run_smart_finetune_smoke(
    repo_dir: str = "/content/SMART",
    run_root: str = "/content/smart_finetune_runs",
    run_tag: str = "",
    train_raw_dirs: Optional[Sequence[str]] = None,
    val_raw_dirs: Optional[Sequence[str]] = None,
    pretrain_ckpt: str = "",
    max_epochs: int = 1,
    accelerator: str = "gpu",
    devices: int = 1,
    num_workers: int = 1,
    train_batch_size: int = 1,
    val_batch_size: int = 1,
    total_steps: int = 128,
    warmup_steps: int = 0,
    lr: float = 5e-4,
    num_future_steps: int = 80,
    install_requirements: bool = False,
    update_repo_if_exists: bool = False,
    run_validation: bool = True,
) -> SmartFinetuneResult:
    run_id = str(run_tag).strip() or time.strftime("smart_smoke_%Y%m%d_%H%M%S", time.gmtime())

    repo_path = _ensure_smart_repo(
        repo_dir=repo_dir,
        update_if_exists=bool(update_repo_if_exists),
    )
    default_raw = str(repo_path / "data" / "valid_demo")
    train_dirs = _normalize_dirs(train_raw_dirs, fallback=default_raw)
    val_dirs = _normalize_dirs(val_raw_dirs, fallback=default_raw)

    run_dir = Path(str(run_root)).expanduser() / run_id
    ckpt_dir = run_dir / "checkpoints"
    cfg_dir = run_dir / "configs"
    train_cfg = cfg_dir / "train_scalable_smoke.yaml"
    val_cfg = cfg_dir / "validation_scalable_smoke.yaml"
    train_processed_dir = str(run_dir / "processed_train")
    val_processed_dir = str(run_dir / "processed_val")

    _write_train_config(
        out_path=train_cfg,
        train_raw_dirs=train_dirs,
        val_raw_dirs=val_dirs,
        train_processed_dir=train_processed_dir,
        val_processed_dir=val_processed_dir,
        max_epochs=int(max_epochs),
        accelerator=str(accelerator),
        devices=int(devices),
        num_workers=int(num_workers),
        train_batch_size=int(train_batch_size),
        val_batch_size=int(val_batch_size),
        total_steps=int(total_steps),
        warmup_steps=int(warmup_steps),
        lr=float(lr),
        num_future_steps=int(num_future_steps),
    )
    _write_val_config(
        out_path=val_cfg,
        val_raw_dirs=val_dirs,
        val_processed_dir=val_processed_dir,
        accelerator=str(accelerator),
        devices=int(devices),
        num_workers=int(num_workers),
        batch_size=int(val_batch_size),
        total_steps=int(total_steps),
        warmup_steps=int(warmup_steps),
        lr=float(lr),
        num_future_steps=int(num_future_steps),
    )

    if bool(install_requirements):
        pip_rc = _run_command(
            ["python", "-m", "pip", "install", "-r", "requirements.txt"],
            cwd=str(repo_path),
        )
        if pip_rc.returncode != 0:
            return SmartFinetuneResult(
                status="failed",
                repo_dir=str(repo_path),
                run_dir=str(run_dir),
                train_config_path=str(train_cfg),
                val_config_path=str(val_cfg),
                ckpt_dir=str(ckpt_dir),
                latest_ckpt_path="",
                train_command="",
                val_command="",
                train_raw_dirs=train_dirs,
                val_raw_dirs=val_dirs,
                message="SMART requirements installation failed.",
                train_rc=int(pip_rc.returncode),
                val_rc=0,
            )

    ckpt_dir.mkdir(parents=True, exist_ok=True)
    train_cmd = [
        "python",
        "train.py",
        "--config",
        str(train_cfg),
        "--save_ckpt_path",
        str(ckpt_dir),
    ]
    if str(pretrain_ckpt).strip():
        train_cmd.extend(["--pretrain_ckpt", str(pretrain_ckpt).strip()])

    train_run = _run_command(train_cmd, cwd=str(repo_path))
    latest_ckpt = _latest_ckpt(ckpt_dir)

    val_cmd: List[str] = []
    val_rc = 0
    if bool(run_validation) and latest_ckpt:
        val_cmd = [
            "python",
            "val.py",
            "--config",
            str(val_cfg),
            "--pretrain_ckpt",
            str(latest_ckpt),
        ]
        val_run = _run_command(val_cmd, cwd=str(repo_path))
        val_rc = int(val_run.returncode)

    status = "success" if (int(train_run.returncode) == 0) else "failed"
    msg = ""
    if not latest_ckpt:
        msg = (
            "Training completed without checkpoint export. "
            "Check SMART logs; if using DDP on single device, verify trainer compatibility."
        )
    elif status != "success":
        msg = "Training command failed."

    return SmartFinetuneResult(
        status=status,
        repo_dir=str(repo_path),
        run_dir=str(run_dir),
        train_config_path=str(train_cfg),
        val_config_path=str(val_cfg),
        ckpt_dir=str(ckpt_dir),
        latest_ckpt_path=str(latest_ckpt),
        train_command=" ".join(train_cmd),
        val_command=" ".join(val_cmd),
        train_raw_dirs=train_dirs,
        val_raw_dirs=val_dirs,
        message=str(msg),
        train_rc=int(train_run.returncode),
        val_rc=int(val_rc),
    )

